package com.rescomms.flutter_push_notifications

const val ACTION_NEW_FB_TOKEN = "ACTION_NEW_FB_TOKEN"
const val EXTRA_TOKEN = "EXTRA_TOKEN"

const val ACTION_REMOTE_MESSAGE = "ACTION_REMOTE_MESSAGE"
const val EXTRA_MESSAGE = "EXTRA_MESSAGE"

const val ACTION_PRESS_PUSH_BUTTON = "ACTION_PRESS_PUSH_BUTTON"
const val EXTRA_PUSH_DATA = "EXTRA_PUSH_DATA"
const val EXTRA_PRESS_ACTION = "EXTRA_PRESS_ACTION"

const val CHANNEL_ID = "123654789369852147"
